### ISSUE TITLE
Action creates a wrong file

### ISSUE THREAD

**Issue by IgnisDa** [microsoft/publish-dev-container-features-action#40]
The devcontainer features expect the features tar to be called `features.tgz`, but this action creates it as `devcontainer-features.tgz`. 

https://github.com/microsoft/publish-dev-container-features-action/blob/b92baddea96faf50b998b9080c1079da78600c51/src/utils.ts#L26

Moreover, it expects the file inside the tgz to be named `features.json`, but the action creates it as `devcontainer-features.json`.

https://github.com/microsoft/publish-dev-container-features-action/blob/b92baddea96faf50b998b9080c1079da78600c51/src/utils.ts#L35

![image](https://user-images.githubusercontent.com/60938164/152461392-cb5542c4-0a24-45bf-9f20-08f003b4eb3f.png)

I can work on a PR to fix the same.

**Comment by IgnisDa** [comment]
Looking at https://github.com/microsoft/vscode-remote-release/issues/5980, it seems like the actual "devcontainers-features" feature is not yet been update to follow `features.json` file. @joshspicer can you please confirm?

**Comment by joshspicer** [comment]
We've recently changed the name everywhere from `features.*` --> `devcontainer-features.*` to avoid future naming collisions.  

All of our tooling should now be updated to expect `devcontainer-features.json`.  Are you using Remote-Containers or Codespaces?   Can you share what version of the devcontainer-cli you see in the logs (should be toward the top).

Today and moving forward, the tooling will explicitly require the release asset to be named `devcontainer-features.tgz`

Once you get updated to the latest version of the tooling, you should update this line to the new name https://github.com/IgnisDa/developrs/blob/main/.github/workflows/deploy-features.yml#L30 (I see what you did is probably a temporary mitigation)

**Comment by IgnisDa** [comment]
Turns out my Vscode was not updated to the latest version. It now works as expected. Thank you for helping me out!

**Comment by joshspicer** [comment]
Appreciate you taking the time to try out features!  @IgnisDa
